version: '3'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/pricer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: LyAGZympuR5yZfAX
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - frontend

  db:
    image: linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=LyAGZympuR5yZfAX
      - TZ=Europe/London
    volumes:
      - /home/debian10/mariadb:/config
    ports:
      - 3306:3306
    restart: always
    networks:
      - backend

networks:
  backend:
  frontend: